version: "2"
services:
  cors-anywhere:
    image: redocly/cors-anywhere
    hostname: cors-anywhere
    ports:
      - "3004:8080"
  products:
    build: ./
    ports:
      - "3003:3003"
    volumes:
      - "./src:/src/src"
    environment:
      PORT: 3003
      REACT_PRODUCT_API:
      REACT_REVIEWS_API:
